
using SK2EVERYONE.Model;

namespace SK2EVERYONE.DAL
{
    public class PatientFirebirdCreateTable : FirebirdCreateTable
    {
        const string sql = "CREATE TABLE PATIENT " +
            "(ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "NAME VARCHAR(50), " +
            "BIRTHNUMBER VARCHAR(20), " +
            "HIHID VARCHAR(20), " +
            "STREET VARCHAR(50), " +
            "CITY VARCHAR(50), " +
            "ZIPCODE VARCHAR(20), " +
            "PHONENUMBER VARCHAR(20), " +
            "MOBILENUMBER VARCHAR(20), " +
            "CONSTRAINT FK_Patient_HIH FOREIGN KEY(HIHID) REFERENCES HIH(ID) ON DELETE NO ACTION ON UPDATE CASCADE)";
        public PatientFirebirdCreateTable(IFirebirdConnectionProvider firebirdConnectionProvider) : base(sql, firebirdConnectionProvider)
        {
        }
    }
}
